### ISSUE TITLE
Missing icon for TriggerParameter

### ISSUE THREAD

**Issue by etehel** [bitfocus/companion-module-smodetech-smodelive#7]
SInce this issue:
https://github.com/dlrd/Smode-Issues/issues/6391
Trigger can now be instanciate in companion, but do not have the correct icon.

Here is the correct one with its encoding in BASE64:
![trigger](https://github.com/bitfocus/companion-module-smodetech-smodelive/assets/40066203/936df828-cf46-48e5-a867-5f0a867e1871)

`iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAYAAABV7bNHAAAABHNCSVQICAgIfAhkiAAABGFJREFUeJztXD1rVEEUPSOLhZImEYuANgaExGAV9Q/4BwKCpTapBCsh/oJI/AtJnz6pU4oRLCQiiLFRsDDRIkGbdXMsZgJx35l9d+bt2406B7aZ9+bcc+/O533zHlBQUFAwPrhxGCXZAXAdwC0ANwFcA3AZwIVwy08AXwF8BPAGwCsA751zv0avdkQguUByjeQ+87EfOBbG7c9QQHI6ONRtEJQYuoF7etx+JoPkHMmdFoISww7JuXH7XQuSUyS3RxiYfmyTnBqmT0MbpEkuA1hJqHIAYAfASwDvAHwB8CNcuwhgGsAsgDsAbgO4lMD91Dn3LOH+9kByguSu4d89JrlF8i79LJZqpxPqbgWuOuySnGjD5xTRC6wfgPdJPiA5zNbqAmfdjNjluGY8kvdqxB2SXByBjsVgaxDuta2jX9TDGkHPRyrIa3peo+nhqIQMajmHJOdHIkRrm69pTe22JPoxJ4bXzBh8W9DYCVpiaGdMop+tYgPyVitGG4B+tlPoso3ZjfGp/MwF5wQDgrQ7bEPLEUOvh2qoBTDe3ZYt9WvXJvRL9wNx6QjAZNMUBP366AqAGfiUB+BTHXsAPjvn2JC/A+A7ANWtLjnnvjXhB+N7q+zZiuR5ko9Jfohwn8aHcO/5BvbmI9zbuZwnxHMR4qx1TgjMuiEoMaznBorxdVJ+FoA6ZXGYyXWfZK9BcE7QI3k/U4NaI+3kcJ0kuxSStw9s1mpiWM/QsRjhSk+60Wfr+rGfwbNpcPaQ5AuSG+H3gvX7K5LczNCjNrhrqTygXhQ+SOQY1HJ6JFdITg6oPxnuGdQ1k1oSfRagH90UjtiW4pgJKQv6MSeGDSZsS+i3DxsD+MxjEn2qROWT7FsQ6u5lXjHTz1axf33JLKTKuxTh7DFhdqNeYdu7GXU/vZtQP9a1soNzijsWJHNXo89M9sM2vtI3ZwVTl6BvPQobVgcMNmLdzdSKGvlIvTg0z170q95+9KwBNtroUHfhxwkcqpdUFo3nRN1boixlMfVIlK0O87Fx4Fo12o5B+VTxXQXopih7abFIP8vNiEttpGAV5wztM63yqeK7CtA1UfbOaPSKKDtyzn031jcjcB4ZNSgonyq+qwBdFmVfjEZV63lrrJsDxa00KCifKr6rAF0QZT9EmYIK7idj3RwobqVBQflU8V0FqOAUVIB+irKLRr6vouyqXU4yFLfSoKB8qviuAqQMWNMBe6LshrFuDhS30qCgfKr4rgL0UZTNGo1+FmUTHLBjz0XgVHlmpUFB+VTxXQXojSi7Y7EYEuzqH3xiqZ8IxbmXkORXPinf/0TZatiMK5TN6imCku6oISgJsxqCknI1EJWkfQ1ReexTQ1QeHBoIy6PnGsJyeMFA/F8ffykHqJoeoApG/tsjeCmGyiHOGmPlGLDBaDlIbhBQXkUwCCkvsxgEldehDOLKC3UGsf/0K5nlpd5Rgv/ga+GtgOXDAjawfJrCDv6lHzcpn8cpKCgoOMP4DRMmAGAFkj1qAAAAAElFTkSuQmCC`

**Comment by ArthurVasseur** [comment]
done https://github.com/bitfocus/companion-module-smodetech-smodelive/commit/413123b2cc2c68be0494b5a8ead8b5b807feb30d
